"""Pydantic contracts shared by the API, the supervisor and the agents.

Two groups:
1. Generic chat contract (ChatAction / ChatArtifact / ChatTraceEvent) — identical
   to cvm-agents so the existing frontend works unchanged.
2. CampaignDraft — the AdConnect-specific domain model. It mirrors the product's
   5-step campaign wizard (Sending Channel → Segments → Message → Cost →
   Confirmation) and is what the builder agent emits as a `campaign_draft`
   artifact for the canvas to render.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field


# ── Generic chat contract ─────────────────────────────────────────────────────

class ChatAction(BaseModel):
    id: str
    label: str
    kind: str = "default"
    payload: dict[str, Any] = Field(default_factory=dict)


class ChatTraceEvent(BaseModel):
    event: str
    status: Literal["info", "warning", "error"] = "info"
    detail: str | None = None
    ts: datetime | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class ChatArtifact(BaseModel):
    id: str
    type: str
    title: str | None = None
    content: dict[str, Any] | None = None
    url: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


# ── Campaign wizard domain model ──────────────────────────────────────────────

# Wizard steps in product order. `ready` is a terminal pseudo-step meaning every
# required slot is filled and the draft can be submitted for moderation.
WizardStep = Literal["channel", "segments", "message", "cost", "confirmation", "ready"]
WIZARD_STEPS: tuple[WizardStep, ...] = ("channel", "segments", "message", "cost", "confirmation")

Channel = Literal["sms", "email", "meta"]
Demographics = Literal["all", "men", "women"]


class SegmentSpec(BaseModel):
    """Audience parameters — the "Segments" wizard step.

    All fields optional; the builder fills them incrementally from the dialogue
    and/or by matching a catalog segment. `matched_segment_id` records when the
    audience came from an operator catalog segment rather than free-form input.
    """
    template: str | None = None
    geography: list[str] = Field(default_factory=list)
    demographics: Demographics = "all"
    age: list[str] = Field(default_factory=list)               # e.g. ["18-25", "45-55"]
    monthly_income: str | None = None
    deposits_per_month: str | None = None
    interests: list[str] = Field(default_factory=list)
    children_age: list[str] = Field(default_factory=list)
    triggers_enabled: bool = False
    matched_segment_id: str | None = None
    matched_segment_name: str | None = None
    # The user actively decided on the audience (picked a segment, described it on
    # the segments step, or chose to continue) — gates leaving the segments step,
    # so the agent always *offers* to pick an audience even if some fields were
    # pre-filled (heuristics/LLM inferring from the product).
    audience_confirmed: bool = False

    def is_specified(self) -> bool:
        """True when the user gave at least one meaningful targeting signal."""
        return bool(
            self.geography
            or self.age
            or self.interests
            or self.children_age
            or self.monthly_income
            or self.deposits_per_month
            or self.demographics != "all"
            or self.matched_segment_id
        )

    def is_ready(self) -> bool:
        """The segments step is complete only after an explicit audience decision."""
        return self.audience_confirmed or bool(self.matched_segment_id)


MetaObjective = Literal["awareness", "traffic", "engagement", "leads", "sales"]

# Publisher platforms (WhatsApp is reached via Click-to-WhatsApp, not a placement).
META_PLACEMENTS: tuple[str, ...] = ("facebook", "instagram", "messenger", "audience_network")


class MetaSpec(BaseModel):
    """Meta-specific campaign config (maps to Campaign objective + Ad Set placements)."""
    objective: MetaObjective = "traffic"
    placements: list[str] = Field(default_factory=lambda: ["facebook", "instagram"])
    lookalike: bool = False
    optimization_goal: str = "link_clicks"


class PlatformStat(BaseModel):
    """Per-publisher-platform forecast row (mirrors an Insights publisher_platform breakdown)."""
    platform: str
    label: str
    impressions: int
    reach: int


class MessageSpec(BaseModel):
    """The creative — the "Message" wizard step."""
    text: str | None = None
    sender: str | None = None
    # Creative variants generated by the agent before one is chosen.
    variants: list[str] = Field(default_factory=list)

    def is_specified(self) -> bool:
        return bool(self.text and self.text.strip())


class CostSpec(BaseModel):
    """Budget and scheduling — the "Cost" wizard step."""
    budget: float | None = None
    messages_count: int | None = None
    start_date: str | None = None
    end_date: str | None = None
    time_from: str | None = None
    time_to: str | None = None
    uniform_distribution: bool = False
    autorun: bool = False

    def is_specified(self) -> bool:
        return self.budget is not None or self.messages_count is not None


class CampaignDraft(BaseModel):
    """Full campaign draft — the contract between the builder agent and the canvas.

    `step` is the first incomplete wizard step (computed by `current_step`).
    Forecast fields (`audience_reach`, `price_per_message`, `estimated_cost`) are
    filled by tools/forecast.py.
    """
    name: str | None = None
    goal: str | None = None                       # the user's original intent, in their words
    product: str | None = None                    # what is being advertised
    channel: Channel | None = None
    segments: SegmentSpec = Field(default_factory=SegmentSpec)
    message: MessageSpec = Field(default_factory=MessageSpec)
    cost: CostSpec = Field(default_factory=CostSpec)
    meta: MetaSpec = Field(default_factory=MetaSpec)   # used when channel == "meta"

    audience_reach: int = 0
    price_per_message: float = 0.0        # messaging channels (SMS/Email)
    estimated_cost: float = 0.0
    cpm: float = 0.0                       # network channels (Meta): ₽ per 1000 impressions
    estimated_impressions: int = 0         # network channels: budget ÷ CPM × 1000
    platform_breakdown: list[PlatformStat] = Field(default_factory=list)  # Meta per-platform split

    status: Literal["draft", "submitted"] = "draft"
    step: WizardStep = "channel"

    def current_step(self) -> WizardStep:
        """First wizard step whose required slots are not yet filled."""
        if self.channel is None:
            return "channel"
        if not self.segments.is_ready():
            return "segments"
        if not self.message.is_specified():
            return "message"
        if not self.cost.is_specified():
            return "cost"
        return "confirmation"

    def is_ready(self) -> bool:
        return self.current_step() == "confirmation"
